# Ensuring all CSVs in target namespace are ready
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-check
  annotations:
    argocd.argoproj.io/hook: PostSync
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: check-csv
          image: quay.io/bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -x

              current_seconds=0
              limit_seconds=$(( $(date +%s) + 2400 ))
              csv_installing=0

              while [ ${current_seconds} -lt ${limit_seconds} ]; do
                if [ $(kubectl get csv -n " {{.Values.metadata.namespace}}" --no-headers | grep -vc Succeeded) -gt 0 ]; then
                  csv_installing=1
                  echo "INFO: CSVs still installing."
                  sleep 60
                else
                  csv_installing=0
                  break
                fi
                current_seconds=$(( $(date +%s) ))
              done

              if [ ${csv_installing} -eq 0 ]; then
                echo "INFO: All CSVs are ready."
              else
                echo "ERROR: CSVs still not ready."
                exit 1
              fi
      restartPolicy: Never
      serviceAccountName: argocd-application-controller
  backoffLimit: 1
