apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-config-dev
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: dev
      name: cluster-config
      key: kubeconfig
