---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system 
spec:
  finalizers:
  - kubernetes 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.4.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: capabilities-shim
  annotations:
    argocd.argoproj.io/sync-wave: "150"
spec:
  ignoreCrossplaneConstraints: false
  package: quay.io/moyingbj/capabilities-shim:v0.0.1
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
