# Ensuring all namespace and cluster scoped resources are cleaned up
apiVersion: v1
kind: Pod
metadata:
  name: hook-postinstall
  namespace: argocd
  annotations:
    "helm.sh/hook": "post-delete"
spec:
  containers:
  - name: hook2-container
    image: quay.io/bitnami/kubectl:latest
    imagePullPolicy: IfNotPresent
    command:
      - /bin/bash
      - -c
      - |
        set -x

        result=0

        # clean csv
        csvs=($(kubectl get csv -n operators -o name))
        if [[ -n ${csvs[@]} ]]; then
          kubectl delete ${csvs[@]} -n operators
          (( result+=$? ))
        fi

        # clean crd
        crds=($(kubectl get crd -o name | grep elastic.co))
        if [[ -n ${crds[@]} ]]; then
          kubectl delete ${crds[@]}
          (( result+=$? ))
        fi

        exit "${result}"
  restartPolicy: Never
  serviceAccountName: argocd-application-controller
  terminationGracePeriodSeconds: 0